name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check PR title. If it contains SKIP, skip this CI test
      run: |
        if [[ $TITLE =~ ^SKIP ]]; then
        echo "PR title starts with 'SKIP'"
        exit 0
        else
        echo "PR title did not start with 'SKIP'"
        exit 0
        fi    
    
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

    - name: Set up Go
      uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 go build -trimpath -a -tags netgo -ldflags '-w -extldflags' -o scorecard-webapp

    - name: Test
      run: CGO_ENABLED=0 go test -trimpath -a -tags netgo -ldflags '-w -extldflags' -o scorecard-webapp
